// examples/todo-react/src/components/top-nav.tsx
/**
 * Three tabs (TODO / Cache / Settings) as a segmented control. On wide
 * screens it rides a centered top bar with the 絆 Kizuna Sync brand; on narrow ones a
 * compact full-width segment bar pins to the bottom (CSS media query toggles
 * which bar shows). No router: the active tab is in-component state lifted to
 * App, matching expo-router's router.replace tab semantics (no history growth).
 * Two badges live here (top bar only), one per durable journal: useRejections
 * counts the writes the server refused, useOverwrites the columns another
 * device won. Each chip is hidden at 0 and opens its own journal on click.
 */

import { useState } from 'react'
import { Chip } from '@heroui/react'
import { useOverwrites, useRejections } from '@kizunasync/react'
import { OverwritesModal } from './overwrites-modal'
import { RejectionsModal } from './rejections-modal'
import { TopNavBrand } from './brand-header'
import { SegmentPill, SegmentPillGroup } from './segment-pill-group'

// MARK: - Segmented nav

export type TTab = 'todo' | 'cache' | 'settings'

interface ITabDef {
  key: TTab
  label: string
  glyph: string
}

const TABS: ITabDef[] = [
  { key: 'todo', label: 'TODO', glyph: '✓' },
  { key: 'cache', label: 'Debug', glyph: '◉' },
  { key: 'settings', label: 'Settings', glyph: '⚙' },
]

export function TopNav({ active, onSelect }: { active: TTab; onSelect: (tab: TTab) => void }) {
  const { rejections, dismiss } = useRejections()
  const { overwrites, dismiss: dismissOverwrite } = useOverwrites()
  const [rejectionsOpen, setRejectionsOpen] = useState(false)
  const [overwritesOpen, setOverwritesOpen] = useState(false)

  return (
    <nav className="topnav" aria-label="Sections">
      <div className="topnav-inner">
        <TopNavBrand />
        <div className="topnav-segment">
          <Segment active={active} onSelect={onSelect} />
        </div>
        {rejections.length > 0 ? (
          <Chip
            color="accent"
            variant="primary"
            role="button"
            tabIndex={0}
            aria-label="Rejections"
            onClick={() => setRejectionsOpen(true)}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                setRejectionsOpen(true)
              }
            }}
          >
            {rejections.length}
          </Chip>
        ) : null}
        {overwrites.length > 0 ? (
          <Chip
            color="default"
            variant="secondary"
            role="button"
            tabIndex={0}
            aria-label="Overwrites"
            onClick={() => setOverwritesOpen(true)}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                setOverwritesOpen(true)
              }
            }}
          >
            {overwrites.length}
          </Chip>
        ) : null}
      </div>
      {rejectionsOpen ? (
        <RejectionsModal
          rejections={rejections}
          onDismiss={(mutationId) => void dismiss(mutationId)}
          onClose={() => setRejectionsOpen(false)}
        />
      ) : null}
      {overwritesOpen ? (
        <OverwritesModal
          overwrites={overwrites}
          onDismiss={(id) => void dismissOverwrite(id)}
          onClose={() => setOverwritesOpen(false)}
        />
      ) : null}
    </nav>
  )
}

export function BottomNav({ active, onSelect }: { active: TTab; onSelect: (tab: TTab) => void }) {
  return (
    <nav className="bottomnav" aria-label="Sections">
      <Segment active={active} onSelect={onSelect} grow />
    </nav>
  )
}

// MARK: - Pieces

function Segment({
  active,
  onSelect,
  grow,
}: {
  active: TTab
  onSelect: (tab: TTab) => void
  grow?: boolean
}) {
  return (
    <SegmentPillGroup ariaLabel="Sections" grow={grow}>
      {TABS.map((tab) => {
        const isActive = tab.key === active

        return (
          <SegmentPill
            key={tab.key}
            isActive={isActive}
            onPress={() => {
              if (!isActive) {
                onSelect(tab.key)
              }
            }}
          >
            <span aria-hidden="true">{tab.glyph}</span>
            {tab.label}
          </SegmentPill>
        )
      })}
    </SegmentPillGroup>
  )
}

// examples/todo-vue/src/components/TopNav.vue
<script setup lang="ts">
/**
 * A centered top bar with the 絆 Kizuna Sync brand + a segmented TODO/Cache/Settings
 * control on large screens; on small screens the brand bar stays and the
 * segment moves to a full-width bottom bar (CSS media query, App.vue renders
 * both placements). Tab state is reactive in App.vue: this only emits intent
 * (router.replace tab semantics: switching never grows a back stack).
 */

import { computed, ref } from 'vue'
import type { TUuid } from 'kizunasync'
import { useOverwrites, useRejections } from 'kizunasync/vue'
import type { IKizunaSyncShim } from '../kizunasync'
import type { TTab } from '../tabs'
import { TABS } from '../tabs'
import OverwritesPanel from './OverwritesPanel.vue'
import RejectionsPanel from './RejectionsPanel.vue'

// MARK: - Segmented nav

const props = defineProps<{ active: TTab; placement: 'top' | 'bottom'; client: IKizunaSyncShim }>()
const emit = defineEmits<{ select: [tab: TTab] }>()

/**
 * App.vue mounts TopNav twice (top + bottom placements); the brand row and
 * these two badges only ever render in the top instance, so only that instance
 * needs the composables (Vue composables don't rely on call order, unlike
 * React hooks, so a prop-gated call is safe). One badge per durable journal:
 * writes the server refused, and columns another device won.
 */
const rejections = props.placement === 'top' ? useRejections({ client: props.client }) : null
const rejectionCount = computed(() => rejections?.rejections.value.length ?? 0)
const showRejections = ref(false)

const overwrites = props.placement === 'top' ? useOverwrites({ client: props.client }) : null
const overwriteCount = computed(() => overwrites?.overwrites.value.length ?? 0)
const showOverwrites = ref(false)

function dismissRejection(mutationId: TUuid): void {
  void rejections?.dismiss(mutationId)
}

function dismissOverwrite(id: number): void {
  void overwrites?.dismiss(id)
}
</script>

<template>
  <nav :class="placement === 'top' ? 'nav nav-top' : 'nav nav-bottom'">
    <div class="nav-inner">
      <div v-if="placement === 'top'" class="nav-brand">
        <span class="nav-glyph" aria-hidden="true">絆</span>
        <span class="nav-wordmark">Kizuna Sync</span>
        <button
          v-if="rejectionCount > 0"
          type="button"
          class="rejections-badge"
          aria-label="Rejections"
          @click="showRejections = true"
        >
          {{ rejectionCount }}
        </button>
        <button
          v-if="overwriteCount > 0"
          type="button"
          class="overwrites-badge"
          aria-label="Overwrites"
          @click="showOverwrites = true"
        >
          {{ overwriteCount }}
        </button>
      </div>
      <div class="segment" role="tablist">
        <button
          v-for="tab in TABS"
          :key="tab.key"
          type="button"
          role="tab"
          :class="active === tab.key ? 'segment-button is-active' : 'segment-button'"
          :aria-selected="active === tab.key"
          @click="emit('select', tab.key)"
        >
          <span class="segment-glyph" aria-hidden="true">{{ tab.glyph }}</span>
          <span class="segment-label">{{ tab.label }}</span>
        </button>
      </div>
    </div>
  </nav>

  <RejectionsPanel
    v-if="placement === 'top' && showRejections"
    :rejections="rejections?.rejections.value ?? []"
    :error="rejections?.error.value ?? null"
    @dismiss="dismissRejection"
    @close="showRejections = false"
  />

  <OverwritesPanel
    v-if="placement === 'top' && showOverwrites"
    :overwrites="overwrites?.overwrites.value ?? []"
    :error="overwrites?.error.value ?? null"
    @dismiss="dismissOverwrite"
    @close="showOverwrites = false"
  />
</template>
