// examples/todo-vue/src/components/SettingsView.vue
<script setup lang="ts">
/**
 * `editAnyone` ("Test non-owner edit") lifts the local read-only guard on the
 * registered users' rows only, so a non-owner write hits RLS (RLS_DENIED, then
 * engine revert). "Live sync" is
 * the realtime switch: off ⇒ the client only syncs on a manual tap. The
 * Network "Offline (simulated)" toggle (default off) emulates airplane mode
 * through the shared `settings` flag: it queues mutations, suspends live
 * sync, and flushes on return (the TodoView SyncBar reads the same flag via
 * UI connectivity). This view only edits `settings`; the binding from
 * `settings` to the engine lives in App.vue so it is wired from first load,
 * whichever tab opens first. Force conflict, expire checkpoint, and reset
 * local stay as on-demand buttons here.
 */

import { ref } from 'vue'
import { t } from '../i18n'
import type { IKizunaSyncShim } from '../kizunasync'
import { settings } from '../settings'

// MARK: - Settings view

const props = defineProps<{ client: IKizunaSyncShim }>()

const message = ref<string | null>(null)

// MARK: - Methods

function runForceConflict(): void {
  void props.client.forceServerConflict().then((verdict) => {
    message.value = verdict
  })
}

function runExpireCheckpoint(): void {
  void props.client.expireCheckpoint().then(() => {
    message.value = 'cursor rewound: next sync re-walks history'
  })
}

function runResetLocal(): void {
  void props.client.resetLocal().then(() => {
    message.value = 'local wiped: sync to re-hydrate the RLS-visible rows'
  })
}
</script>

<template>
  <section class="screen">
    <div class="screen-head">
      <span class="screen-glyph" aria-hidden="true">絆</span>
      <span class="screen-title">{{ t('brand.name') }}</span>
      <span class="screen-sub">{{ t('settings.title') }}</span>
    </div>

    <p class="section-title">live sync</p>
    <button type="button" class="toggle-card" :aria-pressed="settings.live" @click="settings.live = !settings.live">
      <span class="toggle-text">
        <span class="toggle-label">{{ t('settings.liveSync') }}</span>
        <span class="toggle-hint">{{ t('settings.liveSync.hint') }}</span>
      </span>
      <span :class="settings.live ? 'switch is-on' : 'switch'">
        <span class="switch-knob" />
      </span>
    </button>

    <p class="section-title">network</p>
    <button
      type="button"
      class="toggle-card"
      :aria-pressed="settings.offline"
      @click="settings.offline = !settings.offline"
    >
      <span class="toggle-text">
        <span class="toggle-label">Offline (simulated)</span>
        <span class="toggle-hint">
          Queue mutations locally with no network. Live sync is suspended; flip back online to flush
          the outbox and resume.
        </span>
      </span>
      <span :class="settings.offline ? 'switch is-on' : 'switch'">
        <span class="switch-knob" />
      </span>
    </button>

    <p class="section-title">reconciliation</p>
    <button
      type="button"
      class="toggle-card"
      :aria-pressed="settings.editAnyone"
      @click="settings.editAnyone = !settings.editAnyone"
    >
      <span class="toggle-text">
        <span class="toggle-label">{{ t('settings.editAnyone') }}</span>
        <span class="toggle-hint">{{ t('settings.editAnyone.hint') }}</span>
      </span>
      <span :class="settings.editAnyone ? 'switch is-on' : 'switch'">
        <span class="switch-knob" />
      </span>
    </button>

    <p class="section-title">edge-case lab</p>
    <div class="lab">
      <div class="lab-row">
        <button type="button" class="lab-button" @click="runForceConflict">force conflict</button>
        <button type="button" class="lab-button" @click="runExpireCheckpoint">expire checkpoint</button>
        <button type="button" class="lab-button" @click="runResetLocal">reset local</button>
      </div>
      <p class="lab-hint">
        also try: airplane mode, kill the tab mid-outbox, two tabs on one account
      </p>
      <p v-if="message !== null" class="lab-message">{{ message }}</p>
    </div>
  </section>
</template>

// examples/todo-react/src/components/settings-view.tsx
import { useState } from 'react'
import { Button, Switch } from '@heroui/react'
import { messageOf } from '@kizunasync/utilities'
import type { IKizunaSyncShim } from '../kizunasync'
import { t } from '../i18n'
import { Brand } from './brand-header'
import { useSettings } from './settings-context'

// MARK: - Settings view

/**
 * `editAnyone` ("Test non-owner edit") lifts the client-side guard on the
 * registered users' todos only, so a non-owner write reaches the server. The
 * server returns RLS_DENIED and the engine reverts. Every other row on the
 * shared board is already writable. "Live sync" (default on) is the
 * realtime switch: off ⇒ the client only syncs when you tap "sync now". The
 * Network "Offline (simulated)" toggle force-suspends live sync regardless,
 * queues mutations locally, and flushes on flip-back (the SyncBar dot reads
 * the same flag). Force conflict, expire checkpoint, and reset local stay as
 * on-demand buttons.
 */
export function SettingsView({ client }: { client: IKizunaSyncShim }) {
  // MARK: - Variables
  const { editAnyone, setEditAnyone, live, setLive, offline, setOffline } = useSettings()
  const [message, setMessage] = useState<string | null>(null)

  // MARK: - render
  return (
    <div className="column">
      <Brand sub={t('settings.title')} />

      <p className="section-title">live sync</p>
      <ToggleRow
        label={t('settings.liveSync')}
        hint={t('settings.liveSync.hint')}
        value={live}
        onToggle={() => setLive(!live)}
      />

      <p className="section-title">network</p>
      <ToggleRow
        label="Offline (simulated)"
        hint="Queues mutations locally with no network. Live sync is suspended; flip back online to flush the outbox and resume."
        value={offline}
        onToggle={() => setOffline(!offline)}
      />

      <p className="section-title">reconciliation</p>
      <ToggleRow
        label={t('settings.editAnyone')}
        hint={t('settings.editAnyone.hint')}
        value={editAnyone}
        onToggle={() => setEditAnyone(!editAnyone)}
      />

      <p className="section-title">edge-case lab</p>
      <div className="lab-panel">
        <div className="lab-row">
          <LabButton
            label="force conflict"
            onPress={() => {
              void client.forceServerConflict().then(setMessage).catch((cause: unknown) => setMessage(messageOf(cause)))
            }}
          />
          <LabButton
            label="expire checkpoint"
            onPress={() => {
              void client.expireCheckpoint().then(() =>
                setMessage('cursor rewound: next sync re-walks history'),
              ).catch((cause: unknown) => setMessage(messageOf(cause)))
            }}
          />
          <LabButton
            label="reset local"
            onPress={() => {
              // Atomic wipe: store + outbox + attachment sandbox + the Debug rings. The wipe leaves nothing queued, so nothing wakes the engine and the Debug tab stays empty until the next sync.
              void client.resetLocal().then(() => {
                setMessage('local wiped: sync to re-hydrate the RLS-visible rows')
              }).catch((cause: unknown) => setMessage(messageOf(cause)))
            }}
          />
        </div>
        <p className="lab-hint">
          also try: airplane mode, kill the tab mid-outbox, two tabs on one account
        </p>
        {message !== null ? <p className="lab-message">{message}</p> : null}
      </div>
    </div>
  )
}

// MARK: - Pieces

function ToggleRow({
  label,
  hint,
  value,
  onToggle,
}: {
  label: string
  hint: string
  value: boolean
  onToggle: () => void
}) {
  return (
    <Switch.Root className="w-full" isSelected={value} onChange={onToggle} aria-label={label}>
      <Switch.Content className="toggle-card">
        <span className="toggle-card-text">
          <span className="toggle-card-label">{label}</span>
          <span className="toggle-card-hint">{hint}</span>
        </span>
        <Switch.Control>
          <Switch.Thumb />
        </Switch.Control>
      </Switch.Content>
    </Switch.Root>
  )
}

function LabButton({ label, onPress }: { label: string; onPress: () => void }) {
  return (
    <Button variant="outline" size="sm" onPress={onPress}>
      {label}
    </Button>
  )
}
